"""Constants for the EHEIM.digital integration."""

DOMAIN = "eheimdigital"

VERSION_UNDEFINED = 0
VERSION_HC = 1
VERSION_HC_PLUS = 2
VERSION_EHEIM_LIGHT = 3
VERSION_EHEIM_EXT_FILTER = 4
VERSION_EHEIM_EXT_HEATER = 5
VERSION_EHEIM_FEEDER = 6
VERSION_EHEIM_CHILLER = 7
VERSION_EHEIM_LIGHT_AQUAKIDS = 8
